name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Run tests
        run: |
          pytest backend/tests/


  frontend-build:
    name: Frontend Build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

     docker-build:
    name: Docker Build and Security Scan

    needs:
      - backend-test
      - frontend-build

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build backend image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/cicd_backend:${{ github.sha }} \
            ./backend


      - name: Build frontend image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/cicd_frontend:${{ github.sha }} \
            ./frontend


      - name: Scan backend image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/cicd_backend:${{ github.sha }}
          format: table
          severity: CRITICAL,HIGH
          exit-code: 1


      - name: Scan frontend image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/cicd_frontend:${{ github.sha }}
          format: table
          severity: CRITICAL,HIGH
          exit-code: 1


      - name: Push backend image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/cicd_backend:${{ github.sha }}


      - name: Push frontend image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/cicd_frontend:${{ github.sha }}
